import java.awt.image.BufferedImage;
import java.nio.file.Path;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        Bitmap brokenDown = new Bitmap(args[0]);

        switch (args[2].toLowerCase()) {
            case ("greyscale") : brokenDown.greyScale();
            break;
            case ("negative") : brokenDown.negative();
            break;
            case ("rotatecolors") : brokenDown.rotateColors();
            break;
            case ("randomize") : brokenDown.randomize();
            break;
            case ("randomizestructured") : brokenDown.randomizeStructured();
        }

        brokenDown.writeBitmap(args[1]);

    }
}
