import java.awt.image.BufferedImage;
import java.nio.file.Path;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        Bitmap brokenDown = new Bitmap("test");
//        Transformation timeToFixIt = new Transformation(brokenDown);

    }
}
