import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystems;
import java.nio.file.Files;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static StringBuffer checkFile (String fileName) {
        Charset chars = Charset.forName("US-ASCII");
        try (BufferedReader fileReader = Files.newBufferedReader(FileSystems.getDefault().getPath(fileName), chars)) {
            StringBuffer errors = new StringBuffer();
            String currentLine = fileReader.readLine();
            int line = 1;
            while (currentLine != null) {
                if (App.checkLine(currentLine)) errors.append("Line " + line + ": Missing semicolon.\n");
                currentLine = fileReader.readLine();
                line++;
            }
            return errors;
        } catch (IOException e) {
            return null;
        }
    }

    public static boolean checkLine (String line) {
        if (line.contains("if")) return false;
        else if (line.contains("else")) return false;
        else if (line.endsWith("{")) return false;
        else if (line.endsWith("}")) return false;
        else if (line.endsWith(";")) return false;
        else if (line.trim().startsWith("//")) return false;
        else if (line.isEmpty()) return false;
        else return true;
    }

    public static void main(String[] args) {
        System.out.println(new App().checkFile(args[0]));
    }
}
